version: "2.1"

services:
  traefik:
    image: containous/traefik:latest
    volumes:
      - ./config/traefik/traefik.toml:/traefik.toml
      - ./config/traefik/acme.json:/acme.json
      # Path to Docker socket on your machine
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    environment:
      - PUID=${PUID:-99}
      - PGID=${PGID:-99}
      - TZ="UTC"
    networks:
      - internal
    labels:
      - "traefik.frontend.rule=PathPrefix:/dashboard,/api,/metrics,/health"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic=${HTTP_USERNAME}:${HTTP_PASSWORD}"
    restart: always
  deluge:
    image: linuxserver/deluge:latest
    volumes:
      - ./data:/data
      - ./config/deluge:/config
    ports:
      - 8112:8112
    environment:
      - PUID=${PUID:-99}
      - PGID=${PGID:-99}
      - TZ="UTC"
    networks:
      - internal
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/deluge"
      - "traefik.enable=true"
      - "traefik.frontend.auth.basic=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      - "traefik.frontend.headers.customresponseheaders=X-Frame-Options:SAMEORIGIN"
    restart: always
  sonarr:
    image: linuxserver/sonarr:latest
    volumes:
      - ./data:/data
      - ./config/sonarr:/config
      - /dev/rtc:/dev/rtc:ro
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID:-99}
      - PGID=${PGID:-99}
      - TZ="UTC"
    depends_on:
      - jackett
    networks:
      - internal
    labels:
      - "traefik.frontend.rule=PathPrefix:/sonarr"
      - "traefik.enable=true"
      - "traefik.frontend.auth.basic=${HTTP_USERNAME}:${HTTP_PASSWORD}"
    restart: always
  jackett:
    image: linuxserver/jackett:latest
    volumes:
      - ./config/jackett:/config
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID:-99}
      - PGID=${PGID:-99}
    depends_on:
      - deluge
    networks:
      - internal
    labels:
      - "traefik.frontend.rule=PathPrefix:/jackett"
      - "traefik.enable=true"
      - "traefik.frontend.auth.basic=${HTTP_USERNAME}:${HTTP_PASSWORD}"
    restart: always
  radarr:
    image: linuxserver/radarr:latest
    volumes:
      - ./data:/data
      - ./config/radarr:/config
      - /dev/rtc:/dev/rtc:ro
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID:-99}
      - PGID=${PGID:-99}
      - TZ="UTC"
    depends_on:
      - jackett
    networks:
      - internal
    labels:
      - "traefik.frontend.rule=PathPrefix:/radarr"
      - "traefik.enable=true"
      - "traefik.frontend.auth.basic=${HTTP_USERNAME}:${HTTP_PASSWORD}"
    restart: always
  plex:
    image: linuxserver/plex:latest
    volumes:
      - ./config/plex:/config
      - ./data/transcode:/transcode
      - ./data/tv:/data/tvshows
      - ./data/movies:/data/movies
    environment:
      - PUID=${PUID:-99}
      - PGID=${PGID:-99}
      - TZ="UTC"
      - VERSION=latest
    network_mode: host
    restart: always

networks:
  internal:
    driver: bridge

